### ISSUE TITLE
Exposing Publication for dependency

### ISSUE THREAD

**Issue by daddykotex** [coursier/interface#252]
Hi,

First and foremost, thanks for coursier. It's great.

I want to build a small Java wrapper that allows you to pull & run things from an artifact repository such as maven. I tried to build it with `coursier-interface`, because I'd like it to have as few dependencies as possible.

I got very far, my only blocker is that I can't specify the extension of the file I want to pull. For instance, I want to resolve protoc 3.18.2 executable. It's available in here: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.18.2/.

My lib builds `https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.18.2/protoc-3.18.2-osx-aarch_64.jar: not found: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.18.2/protoc-3.18.2-osx-aarch_64.jar` but I'd like to download the  `exe` instead.

Is there any reason `publication` is not available through this wrapper and if no, would you be open to a PR?

Thanks

**Comment by alexarchambault** [comment]
> Is there any reason `publication` is not available through this wrapper and if no, would you be open to a PR?

No reason, apart from me or anyone not needing it here until now. Definitely open to a PR!

**Comment by Flowdalic** [comment]
Is this still an open issue given that https://github.com/coursier/interface/pull/254 was merged?

**Comment by daddykotex** [comment]
Forgot to close!

**Comment by daddykotex** [comment]
Available in https://github.com/coursier/interface/releases/tag/v1.0.8
